// Selector map for Lever application forms.
//
// STUB — placeholder values, not verified against real tenants. Lever forms
// historically use name="name", name="email", name="phone", name="org",
// name="urls[LinkedIn]", name="urls[GitHub]", name="urls[Portfolio]". Custom
// per-tenant questions get autogenerated IDs.
//
// Verify against jobs.lever.co/<slug>/<id>/apply before extending.

globalThis.AutoApplySelectors_lever = {
  full_name: 'input[name="name"]',
  email: 'input[name="email"]',
  phone: 'input[name="phone"]',
  current_company: 'input[name="org"]',
  linkedin: 'input[name="urls[LinkedIn]"]',
  github: 'input[name="urls[GitHub]"]',
  portfolio: 'input[name="urls[Portfolio]"]',
};
